version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # L'API écoute sur le port 3001 par défaut
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./40bierges
      dockerfile: Dockerfile
    ports:
      - "80:3000" #Port 80 (HTTP standard)
    restart: always
    environment:
      - WDS_SOCKET_PORT=0 # Évite les erreurs de websocket avec react-scripts
    depends_on:
      - api
